// <auto-generated />
using System;
using HowToDoItApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HowToDoItApp.Migrations
{
    [DbContext(typeof(HowToDoItContext))]
    [Migration("20260725144118_InitialHowToDoIt")]
    partial class InitialHowToDoIt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("howtodoit")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HowToDoItApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "howtodoit");
                });

            modelBuilder.Entity("HowToDoItApp.Models.StepImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("WorkStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkStepId");

                    b.ToTable("StepImages", "howtodoit");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("WorkSequences", "howtodoit");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("WorkSequenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkSequenceId");

                    b.ToTable("WorkSteps", "howtodoit");
                });

            modelBuilder.Entity("HowToDoItApp.Models.StepImage", b =>
                {
                    b.HasOne("HowToDoItApp.Models.WorkStep", "WorkStep")
                        .WithMany("Images")
                        .HasForeignKey("WorkStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkStep");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkSequence", b =>
                {
                    b.HasOne("HowToDoItApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkStep", b =>
                {
                    b.HasOne("HowToDoItApp.Models.WorkSequence", "WorkSequence")
                        .WithMany("Steps")
                        .HasForeignKey("WorkSequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSequence");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkSequence", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("HowToDoItApp.Models.WorkStep", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
